// Package gocldr is the module root. It carries no API of its own; the usable
// packages are gocldr/datetime, gocldr/number, and gocldr/plural, with the
// per-locale CLDR data opt-in via gocldr/locales/<tag> (both domains) or
// gocldr/locales/all.
//
// The cross-domain locale umbrellas under locales/ are regenerated by
// `go run ./internal/gen`, which gen/generate.sh runs AFTER the per-domain
// generators so the umbrellas track the locale sets just produced. There is
// deliberately no //go:generate directive here: `go generate ./...` visits the
// module root first, where the umbrella run would see stale per-domain data.
package gocldr
