// Code generated by internal/gen. DO NOT EDIT.

// Package all registers all CLDR locale data for both datetime and number.
package all

import (
	_ "github.com/hakastein/gocldr/datetime/locales/all"
	_ "github.com/hakastein/gocldr/number/locales/all"
)
