// Code generated by internal/gen. DO NOT EDIT.

// Package locale registers both datetime and number CLDR data for one locale.
package locale

import (
	_ "github.com/hakastein/gocldr/datetime/locales/en-DK"
	_ "github.com/hakastein/gocldr/number/locales/en-DK"
)
