// Package datetime provides CLDR-based date/time formatting for Go, generated
// directly from the Unicode CLDR data (cldr-dates-full). It has ZERO external
// dependencies (standard-library time only) and is designed to match the
// behaviour of JavaScript's Intl.DateTimeFormat (ECMA-402) for
// the dateStyle/timeStyle styles and the common component options.
//
// The symbol/pattern tables in tables_gen.go are produced by the generator in
// internal/gen. Regenerate them with `make gen` (pinned Docker toolchain).
//
// Usage:
//
//	out := datetime.Format("en", t, datetime.Options{DateStyle: "long", TimeStyle: "short"})
package datetime

import (
	"strings"
	"time"

	"github.com/hakastein/gocldr/datetime/internal/data"
	"github.com/hakastein/gocldr/internal/locale"
)

// The generator reads its CLDR input base from the CLDR_DATA environment
// variable (a node_modules tree set by the pinned gen image). Both the Go
// tables and the Node-produced golden fixtures are regenerated by
// `go generate ./datetime/...` — run via `make gen`, never on the host.
//go:generate go run ./internal/gen -out tables_gen.go
//go:generate node internal/gen/fixtures.js

// Options mirrors the commonly used subset of Intl.DateTimeFormatOptions (ECMA-402).
// Empty strings / nil pointers mean "unset".
type Options struct {
	Hour12                 *bool
	Weekday                string // "long" | "short" | "narrow"
	Era                    string // "long" | "short" | "narrow"
	Year                   string // "numeric" | "2-digit"
	Month                  string // "numeric" | "2-digit" | "long" | "short" | "narrow"
	Day                    string // "numeric" | "2-digit"
	Hour                   string // "numeric" | "2-digit"
	Minute                 string // "numeric" | "2-digit"
	Second                 string // "numeric" | "2-digit"
	TimeZoneName           string // "long" | "short" | "shortOffset" | "longOffset" | "shortGeneric" | "longGeneric"
	DateStyle              string // "full" | "long" | "medium" | "short"
	TimeStyle              string // "full" | "long" | "medium" | "short"
	DayPeriod              string // "narrow" | "short" | "long"
	FractionalSecondDigits *int   // 1..3
	Calendar               string // only the Gregorian calendar is implemented; other values are ignored
	NumberingSystem        string // overrides the locale default
	TimeZone               string // IANA name; an unrecognized name falls back to UTC; empty formats t in the zone it carries
}

// resolveLocale walks the CLDR fallback chain to find a locale registered in
// the locale-data registry: exact id -> explicit parentLocale -> truncate
// trailing subtag -> "en" as the ultimate root substitute. Locale data is
// populated by the imported gocldr/datetime/locales/* packages. The walk never
// matches "und": its registered root patterns are deliberately skipped so
// unknown locales degrade to "en" output instead.
func resolveLocale(loc string) (*data.LocaleData, string) {
	tag, ok := locale.Resolve(loc, parentLocaleMap, func(t string) bool {
		if t == "und" {
			return false
		}
		_, ok := data.Lookup(t)
		return ok
	})
	if ok {
		ld, _ := data.Lookup(tag)
		return ld, tag
	}
	if ld, ok := data.Lookup("en"); ok {
		return ld, "en"
	}
	return nil, ""
}

// Format renders t for the given locale according to opts, matching
// Intl.DateTimeFormat semantics for dateStyle/timeStyle and common component
// options. The locale is a BCP-47 string; unknown locales fall back through the
// CLDR parent chain to en.
func Format(locale string, t time.Time, opts Options) string {
	ld, resolved := resolveLocale(locale)
	if ld == nil {
		return t.Format(time.RFC3339)
	}

	if opts.FractionalSecondDigits != nil {
		if n := *opts.FractionalSecondDigits; n < 1 || n > 3 {
			opts.FractionalSecondDigits = nil
		}
	}

	zoneID := ""
	canonicalZone := ""
	observesDST := false
	if opts.TimeZone != "" {
		loc, err := time.LoadLocation(opts.TimeZone)
		if err != nil {
			opts.TimeZone = "UTC"
			loc = time.UTC
		}
		t = t.In(loc)
		canonicalZone = opts.TimeZone
		zoneID = cldrZoneID(opts.TimeZone)
		observesDST = zoneObservesDST(t)
	}

	zoneName, off := t.Zone()
	isUTC := off == 0 && (zoneName == "UTC" || zoneName == "" ||
		strings.EqualFold(opts.TimeZone, "UTC") || strings.EqualFold(opts.TimeZone, "Etc/UTC"))

	ns := opts.NumberingSystem
	if ns == "" {
		ns = ld.NumberingSystem
	}
	digits := numberingSystemDigits[ns]

	ctx := &formatCtx{ld: ld, locale: resolved, digits: digits, opts: opts, zoneID: zoneID, canonicalZone: canonicalZone, zoneObservesDST: observesDST, isUTC: isUTC}

	pattern := ctx.resolvePattern()
	out := ctx.interpret(pattern, t)
	// node/ICU normalizes the narrow no-break space (U+202F) that recent CLDR
	// data places before day periods back to a regular space; mirror that so we
	// match Intl output. The regular no-break space (U+00A0) is preserved.
	return strings.ReplaceAll(out, " ", " ")
}

// resolvePattern selects the CLDR pattern string to interpret based on opts.
func (c *formatCtx) resolvePattern() string {
	o := c.opts
	hasDate := o.DateStyle != ""
	hasTime := o.TimeStyle != ""

	if hasDate || hasTime {
		var datePat, timePat string
		if hasDate {
			datePat = c.ld.DateFormats[o.DateStyle]
		}
		if hasTime {
			timePat = c.ld.TimeFormats[o.TimeStyle]
			timePat = c.applyHourCycle(timePat)
		}
		switch {
		case hasDate && hasTime:
			return c.combineDateTime(o.DateStyle, datePat, timePat)
		case hasDate:
			return datePat
		default:
			return timePat
		}
	}

	// Component options -> build skeleton, best-match against availableFormats.
	skel := c.buildSkeleton()
	if skel == "" {
		if o.FractionalSecondDigits != nil {
			// Fraction-only request: Intl renders the bare fraction.
			return strings.Repeat("S", *o.FractionalSecondDigits)
		}
		// No options at all: Intl defaults to numeric y/M/d.
		skel = "yMd"
	}
	pat := c.bestMatch(skel)
	pat = c.applyHourCycle(pat)
	// Without seconds, specific/offset zone names attach with a plain space;
	// see normalizeZoneSeparator.
	if o.Second == "" {
		switch o.TimeZoneName {
		case "short", "long", "shortOffset", "longOffset":
			pat = normalizeZoneSeparator(pat)
		}
	}
	// fractionalSecondDigits never appears in availableFormats, so best-fit /
	// synthesis never carries the S field into the resolved pattern. Mirror ICU's
	// adjustFieldTypes by injecting the fractional-second field adjacent to the
	// seconds field after matching.
	if o.FractionalSecondDigits != nil {
		pat = c.injectFractionalSecond(pat, *o.FractionalSecondDigits)
	}
	return pat
}

// injectFractionalSecond places the locale's decimal separator and an S-run
// immediately after the seconds field of pattern, matching ICU's
// adjustFieldTypes (which uses the number decimal separator, e.g. fr ","). The
// separator is emitted as a pattern literal; CLDR decimal separators are
// punctuation, so they pass through interpret unquoted.
func (c *formatCtx) injectFractionalSecond(pattern string, digits int) string {
	toks := tokenizePattern(pattern)
	last := -1
	for i, tok := range toks {
		if tok.letter == 's' {
			last = i
		}
	}
	if last < 0 {
		return pattern
	}
	var b strings.Builder
	for i, tok := range toks {
		b.WriteString(tok.text)
		if i == last {
			b.WriteString(c.ld.DecimalSep)
			b.WriteString(strings.Repeat("S", digits))
		}
	}
	return b.String()
}

// combineDateTime joins a date and a time pattern with the locale's
// dateTimeFormats connector for the given style. Intl prefers the
// dateTimeFormats-atTime connector, keyed by the date style.
func (c *formatCtx) combineDateTime(style, datePat, timePat string) string {
	conn := c.ld.AtTime[style]
	if conn == "" {
		conn = c.ld.DateTime[style]
	}
	return combine(conn, datePat, timePat)
}

// combine substitutes {1}=date and {0}=time into a CLDR combiner pattern,
// honoring single-quoted literals in the combiner.
func combine(combiner, datePat, timePat string) string {
	if combiner == "" {
		return strings.TrimSpace(datePat + " " + timePat)
	}
	var b strings.Builder
	for _, tok := range tokenizePattern(combiner) {
		text := tok.text
		// Quoted literals keep their markers verbatim so the interpreter still
		// treats the segment as a literal; placeholders inside them stay text.
		if tok.letter == 0 && !strings.HasPrefix(text, "'") {
			text = strings.ReplaceAll(text, "{0}", timePat)
			text = strings.ReplaceAll(text, "{1}", datePat)
		}
		b.WriteString(text)
	}
	return b.String()
}
