// Code generated by internal/gen. DO NOT EDIT.

// Package locale registers both datetime and number CLDR data for one locale.
package locale

import (
	_ "github.com/hakastein/gocldr/datetime/locales/ms-Arab-BN"
	_ "github.com/hakastein/gocldr/number/locales/ms-Arab-BN"
)
